### ISSUE TITLE
Plugin availability on RocketModFix

### ISSUE THREAD

**Issue by d3adwolf** [Pustalorc/GlobalBan#14]
Should we expect your plugin on RocketMod again, due to the development of [RocketModFix](https://github.com/RocketModFix/RocketModFix)?

**Comment by Pustalorc** [comment]
No.
If I ever try to make it work for Rocketmod it will be for [LDM](https://github.com/smartlyDressedGames/Legally-Distinct-Missile/). I will not be moving anything of mine to [RMF](https://github.com/RocketModFix/RocketModFix).
However, it is Highly unlikely however for this repo to return to Rocketmod. If you need a moderation plugin, original globalban should still work, and if not then Moderation exists, but I'm sure there's a version of GlobalBan for rocketmod that still works.
